version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: mvp_postgres
    restart: always
    environment:
      POSTGRES_DB: mvp
      POSTGRES_USER: mvp
      POSTGRES_PASSWORD: mvp123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
